apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    ssh:
      publicKeyPath: /var/lib/jenkins/.ssh/id_rsa.pub
